name: Project Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - name: Get Git Version
        uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
        with:
          args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""

      - name: Build
        run: >-
          dotnet build -o out
          --configuration Release          
          --version-prefix "$(cat /home/runner/work/GotenbergSharpApiClient/GotenbergSharpApiClient/version.txt)"

      - name: Install nuget
        run: sudo apt-get install nuget

      - name: Add private GitHub registry to NuGet
        run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/ChangemakerStudios/index.json -Username ChangemakerStudios -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: nuget push ./GotenbergSharpApiClient/GotenbergSharpApiClient/out/*.nupkg -Source "GPR" -SkipDuplicate
